version: '3' 

services:
  registry:
    image: registry:2.5.0 
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - default
    
  jenkins-master:
    image: localhost:5000/fmc-jenkins:0.1
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/jenkins
      - com.df.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    networks: 
      - proxy
      - default
    depends_on:
      - registry

networks:
  proxy:
    external: true
  default:
    external: false
