version: '3'  

services:

  registry:
    image: registry:2.5.0
    ports:
      - 5000:5000
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - default
networks:
  default:
    external: false
